### ISSUE TITLE
当前下单线程时间段-2022-05-01 09:00:00 至 2022-05-01 21:00:00 返回信息:获取履约配送信息异常

### ISSUE THREAD

**Issue by TUANZHANGDDD** [guyongzx/SamsClub_buy#1]
大佬 order.py运行后返回的：获取履约配送信息异常 这种提示是因为山姆没放号还是我那配置错了

**Comment by TUANZHANGDDD** [comment]
> 店铺id和配送模板不匹配,也就是不在一个区域会报这个 你是手动改过吗

没改过哇。。。。。。

**Comment by guyongzx** [comment]
再检查下购物车里是不是收货地址的购物车

**Comment by TUANZHANGDDD** [comment]
> 再检查下购物车里是不是收货地址的购物车

更新：是因为配送网点变了 已解决 感谢
