### ISSUE TITLE
大佬您好，使用pycharm运行报错怎么办啊

### ISSUE THREAD

**Issue by shenrui522** [guyongzx/SamsClub_buy#5]
Traceback (most recent call last):
  File "C:/Users/yue/Desktop/SamsClub_buy-master/sam_buy_bao_gong.py", line 547, in <module>
    address, store, uid = init()
  File "C:/Users/yue/Desktop/SamsClub_buy-master/sam_buy_bao_gong.py", line 498, in init
    address = address_list()
  File "C:/Users/yue/Desktop/SamsClub_buy-master/sam_buy_bao_gong.py", line 46, in address_list
    addressList = myRet['data'].get('addressList')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by guyongzx** [comment]
该填的参数都填了吗,如auth-token这些

**Comment by shenrui522** [comment]
![image](https://user-images.githubusercontent.com/74391936/167289842-088c2c0f-7cc6-4ad2-87d6-8e9828faeaa7.png)我是这样填的，代码能力比较差呜呜呜

**Comment by shenrui522** [comment]
> 该填的参数都填了吗,如auth-token这些
![image](https://user-images.githubusercontent.com/74391936/167289934-c4585aca-5dbe-4efa-82a1-bb3df159096e.png)
我是这么填的，然后还有别的地方要改吗，包我都pip install确认了一遍了

**Comment by guyongzx** [comment]
看这个authtoken的长度好像不大对,检查下抓包的数据对不对
另外可以打印一下40行的myRet
print(myRet)
看下返回是什么

**Comment by shenrui522** [comment]
> 看这个authtoken的长度好像不大对,检查下抓包的数据对不对 另外可以打印一下40行的myRet,(对应你的图里应该是45行) print(myRet) 看下返回是什么

大佬成功了！谢谢大佬！听我说谢谢你，因为有你，温暖了四季！！！！非常感谢！！！

**Comment by guyongzx** [comment]
没事,那我关issue了,另外建议不要公开自己的authtoken

**Comment by shenrui522** [comment]
大佬又出现了一个新问题这个是啥原因呢
getCapacityData [Error]: Expecting value: line 1 column 1 (char 0)

**Comment by shenrui522** [comment]
好像是运行了几分钟以后就会出现这个QAQ

**Comment by guyongzx** [comment]
第几行报错啊

**Comment by shenrui522** [comment]
后面应该是网络的问题！运行一段时间以后会报错这个问题只出现了一次，第二次就好了，已经吃上瑞士卷了！谢谢大佬！


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: guyong ***@***.***&gt;
发送时间: 2022年5月8日 20:48
收件人: guyongzx/SamsClub_buy ***@***.***&gt;
抄送: shenrui522 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[guyongzx/SamsClub_buy] 大佬您好，使用pycharm运行报错怎么办啊 (Issue #5)





 
第几行报错啊
